for _ in range(10):
    print("hola mundo")
    print("xd")
    print("xdxd")
    print("xdxdxd")
    print("xdxdxdxd")
    print("xdxdxdxdxd")
    print("Xd")
    print("xdxdxdxdxdxd")
    print("xdxdxdxdxdxdxd")
    print("xdxdxdxdxdxdxdxd")
    print("xdxdxdxdxdxdxdxdxd")
    print("xdxdxdxdxdxdxdxdxdxd")
